### ISSUE TITLE
Best practice to maintain Retro-compatibility?

### ISSUE THREAD

**Issue by linonetwo** [tyd-format/TyD#4]
In https://github.com/IcyVines/Starbound-RPG-Growth/pull/9#issuecomment-513563271

An author of Starbound Mod "EE for Starbound" propose a patch for Mod "RPG-Growth" to know about his mod.

In my opinion, this approach has three drawbacks:

1. author of "EE for Starbound" have to notify and push some other Mod author for a change
1. the adaption of change might be slow
1. future change in "EE for Starbound" may require an update in all those Mods

What is your opinion, Tynan?

**Comment by linonetwo** [comment]
I know this is a question not very related to TyD, maybe it is about Mod system design, so closing this first.

**Comment by AlbertoRota** [comment]
Regarding the three points you mentioned they all have a common root cause: **Retro-compatibility**.

Ensuring retro-compatibility between older and newer versions of EE for Starbound is responsibility of its author (In this particular case, me).

With that in mind, all three points are solved and no longer an issue _unless_ a breaking change is done in EE for Starbound, and that, again, will be my only fault and responsibility.
